### PR TITLE
add uint32 slice sort

### PR DESCRIPTION
**Pull request by imxyb**
Signed-off-by: imxyb <xyb4638@gmail.com>

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by imxyb** [comment]
PTAL @flycash

**Comment by AlexStocks** [comment]
LGTM

**Comment by wongoo** [comment]
LGTM

**Comment by AlexStocks** [comment]
LGTM

**Pull request merged**
